import { expect, test } from '@playwright/test'
import { foundationDemo, observePageErrors, resetBrowserFixture, signIn } from '../Support/acceptance.mjs'

test.beforeAll(() => resetBrowserFixture())

const row = (page, id) => page.locator(`tr[data-row-id="${id}"]`)
const metric = (page, key) => page.locator(`[data-category-metric="${key}"]`)

test('CA-016 canonical navigation, fixture metrics, direct usage and separate states', async ({ page }) => {
    const noErrors = observePageErrors(page)
    await signIn(page, 'central', foundationDemo.centralAdmin)
    await expect(page.locator('[data-screen-id="CA-001"]')).toBeVisible()
    const nav = page.getByRole('navigation', { name: 'Central Admin sections' })
    await expect(nav.getByRole('link', { name: 'Categories', exact: true })).toHaveCount(1)
    await nav.getByRole('link', { name: 'Categories', exact: true }).click()
    await expect(page).toHaveURL(/\/admin\/central\/categories$/)
    await expect(page.locator('[data-screen-id="CA-016"][data-fixture-version="categories-list-v1"]')).toBeVisible()
    for (const [key, value] of Object.entries({ total: 34, active: 15, 'with-schema': 6, 'missing-translations': 11, 'needs-review': 19 })) {
        await expect(metric(page, key).locator('strong')).toHaveText(String(value))
    }
    await expect(metric(page, 'active')).toContainText('44.1% of total')
    for (const [key, value] of Object.entries({ products: 3, attributes: 2, facets: 1, sites: 3 })) {
        await expect(row(page, 194004).locator(`[data-category-count="${key}"]`)).toHaveText(String(value))
    }
    await expect(row(page, 194004)).toContainText('Parent: Electronics')
    await expect(row(page, 194004).locator('.category-list-status')).toHaveText('Active')
    await expect(row(page, 194004).locator('.category-list-schema')).toHaveText('Approved')
    await expect(row(page, 194006)).toContainText('Level 3 · Parent: Gaming Monitors')
    await expect(row(page, 194006).locator('.category-list-translations')).toContainText('0 missing · 1 outdated')
    const screen = page.locator('[data-screen-id="CA-016"]')
    for (const text of ['Import Categories', 'Market', 'from last month', '+3.1%', 'Duplicate', 'Approve Schema']) {
        await expect(screen.getByText(text, { exact: false })).toHaveCount(0)
    }
    await expect(screen.locator('input[type="checkbox"]')).toHaveCount(0)
    noErrors()
})

test('CA-016 search, combined filters, clear, sorting, pagination and browser back', async ({ page }) => {
    const noErrors = observePageErrors(page)
    await signIn(page, 'central', foundationDemo.centralAdmin)
    await expect(page.locator('[data-screen-id="CA-001"]')).toBeVisible()
    await page.goto('/admin/central/categories')
    await page.locator('#category-search').fill('registry-gaming')
    await expect(page).toHaveURL(/q=registry-gaming/)
    await expect(page.locator('tbody tr[data-row-id]')).toHaveCount(1)
    await page.locator('#category-level').selectOption('2')
    await expect(page).toHaveURL(/level=2/)
    await page.locator('#category-status').selectOption('active')
    await expect(page).toHaveURL(/status=active/)
    await page.locator('#category-schema').selectOption('draft')
    await expect(page).toHaveURL(/schema=draft/)
    await page.locator('#category-site').selectOption('194010')
    await expect(page).toHaveURL(/site=194010/)
    await page.locator('#category-locale').selectOption('3')
    await expect(page).toHaveURL(/locale=3/)
    await expect(row(page, 194005).locator('.category-list-translations')).toHaveText(/Missing.*en-US/)
    await expect(page.locator('[data-category-active-filter-count]')).toContainText('6 active filters')
    await page.getByRole('link', { name: 'Clear filters', exact: true }).click()
    const clearUrl = new URL(page.url())
    for (const key of ['q', 'level', 'status', 'schema', 'site', 'locale', 'page']) expect(clearUrl.searchParams.has(key)).toBe(false)
    await page.getByRole('columnheader', { name: /Products/ }).getByRole('link').click()
    await expect(page).toHaveURL(/sort=products&direction=asc/)
    await page.getByRole('columnheader', { name: /Products/ }).getByRole('link').click()
    await expect(page).toHaveURL(/sort=products&direction=desc/)
    await expect(page.locator('tbody tr[data-row-id]').first()).toContainText('Accessories')
    await page.getByRole('link', { name: 'Next page', exact: true }).click()
    await expect(page).toHaveURL(/page=2/)
    await expect(page.locator('.category-list-pagination')).toContainText('Showing 21 to 34 of 34 categories')
    await page.goBack()
    await expect(page).toHaveURL(/direction=desc/)
    expect(new URL(page.url()).searchParams.has('page')).toBe(false)
    await page.locator('#categories-per-page').selectOption('50')
    await expect(page).toHaveURL(/per_page=50/)
    await expect(page.locator('tbody tr[data-row-id]')).toHaveCount(34)
    await page.locator('#category-search').fill('no-matching-category')
    await expect(page).toHaveURL(/q=no-matching-category/)
    await expect(page.getByRole('heading', { name: 'No matching categories' })).toBeVisible()
    await page.goto('/admin/central/categories?status=active&page=99&sort=products&direction=desc')
    await expect(page.getByRole('heading', { name: 'No categories on this page' })).toBeVisible()
    await page.locator('#categories-page-empty').getByRole('link', { name: 'First page', exact: true }).click()
    await expect(page).toHaveURL(/status=active/)
    expect(new URL(page.url()).searchParams.get('page')).toBe('1')
    await expect(page.locator('tbody tr[data-row-id]')).toHaveCount(15)
    noErrors()
})

test('CA-016 legal lifecycle actions persist through reload and keyboard confirmation', async ({ page }) => {
    const noErrors = observePageErrors(page)
    await signIn(page, 'central', foundationDemo.centralAdmin)
    await expect(page.locator('[data-screen-id="CA-001"]')).toBeVisible()
    await page.goto('/admin/central/categories?q=registry-coffee')
    const coffee = row(page, 194002)
    await coffee.locator('summary').focus()
    await coffee.locator('summary').press('ArrowDown')
    await expect(coffee.getByRole('menuitem', { name: 'Edit', exact: true })).toBeFocused()
    await coffee.getByRole('menuitem', { name: 'Activate', exact: true }).click()
    let dialog = page.getByRole('dialog', { name: 'Activate Coffee Machines?' })
    await dialog.getByRole('button', { name: 'Activate Category' }).focus()
    await dialog.getByRole('button', { name: 'Activate Category' }).press('Enter')
    await expect(coffee.locator('.category-list-status')).toHaveText('Active')
    await page.reload()
    await expect(coffee.locator('.category-list-status')).toHaveText('Active')
    await coffee.locator('summary').click()
    await coffee.getByRole('menuitem', { name: 'Archive', exact: true }).click()
    dialog = page.getByRole('dialog', { name: 'Archive Coffee Machines?' })
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(coffee.locator('.category-list-status')).toHaveText('Active')
    await coffee.locator('summary').click()
    await coffee.getByRole('menuitem', { name: 'Archive', exact: true }).click()
    await dialog.getByRole('button', { name: 'Archive Category' }).click()
    await expect(coffee.locator('.category-list-status')).toHaveText('Archived')
    await coffee.locator('summary').click()
    await expect(coffee.getByRole('menuitem', { name: 'Activate', exact: true })).toHaveCount(0)
    await coffee.getByRole('menuitem', { name: 'Restore', exact: true }).click()
    await page.getByRole('dialog', { name: 'Restore Coffee Machines?' }).getByRole('button', { name: 'Restore Category' }).click()
    await page.reload()
    await expect(coffee.locator('.category-list-status')).toHaveText('Draft')
    noErrors()
})

for (const [width, height] of [[1440, 1000], [1024, 900], [768, 1024], [390, 844]]) {
    test(`CA-016 ${width}px contains tables, filters and action overlays`, async ({ page }) => {
        const noErrors = observePageErrors(page)
        await page.setViewportSize({ width, height })
        await signIn(page, 'central', foundationDemo.centralAdmin)
        await expect(page.locator('[data-screen-id="CA-001"]')).toBeVisible()
        await page.goto('/admin/central/categories?q=registry-gaming')
        const category = row(page, 194005)
        await expect(category).toBeVisible()
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
        await category.locator('summary').scrollIntoViewIfNeeded()
        await category.locator('summary').press('ArrowDown')
        const box = await category.locator('[data-admin-row-actions-panel]').boundingBox()
        expect(box.x).toBeGreaterThanOrEqual(0)
        expect(box.x + box.width).toBeLessThanOrEqual(width)
        expect(box.y).toBeGreaterThanOrEqual(0)
        await expect.poll(async () => {
            const positioned = await category.locator('[data-admin-row-actions-panel]').boundingBox()
            return positioned.y + positioned.height
        }).toBeLessThanOrEqual(height)
        await category.locator('summary').press('Escape')
        if (width === 390) {
            await expect(category).toHaveCSS('display', 'grid')
            for (const key of ['products', 'attributes', 'facets', 'sites']) await expect(category.locator(`[data-category-count="${key}"]`)).toBeVisible()
            await expect(category.locator('.category-list-updated')).toBeVisible()
            await page.locator('#category-sort').selectOption('products')
            await expect(page).toHaveURL(/sort=products/)
            await page.getByRole('button', { name: /open.*navigation|toggle.*navigation/i }).click()
            await expect(page.getByRole('navigation', { name: 'Central Admin sections' })).toBeVisible()
        }
        noErrors()
    })
}

test('CA-016 refuses a Translator without Category capability', async ({ page }) => {
    await signIn(page, 'central', foundationDemo.translator)
    await expect(page.locator('[data-screen-id="CA-001"]')).toBeVisible()
    const response = await page.goto('/admin/central/categories')
    expect(response.status()).toBe(403)
    await expect(page.locator('[data-screen-id="CA-016"]')).toHaveCount(0)
})
