import { bootAdminDrawers } from './admin/drawer';
import { bootAdminModals } from './admin/modal';
import { bootAdminFormStates } from './admin/form-state';
import { bootAdminFilterDrawers } from './admin/filter-drawer';
import { bootAdminFeedback } from './admin/feedback';
import { bootAdminTableSelection } from './admin/table-selection';
import { bootAdminTabs } from './admin/tabs';
import { bootAdminSelects } from './admin/select';
import { bootAdminDatePickers } from './admin/date-picker';
import { bootSearchableSelects } from './admin/searchable-select';
import { bootColorInputs } from './admin/color-input';
import { bootActionProgress } from './admin/action-progress';
import { bootBrandList } from './admin/brand-list';
import { bootAdminUserMenus } from './admin/user-menu';
import { bootCentralNavigation } from './admin/navigation';
import { bootSiteAdminNavigation } from './admin/site-navigation';
import { bootFilterDrawers } from './public/filter-drawer';
import { bootFacetForms } from './public/facet-form';

bootAdminDrawers();
bootAdminModals();
bootAdminFormStates();
bootAdminFilterDrawers();
bootAdminFeedback();
bootAdminTableSelection();
bootAdminTabs();
bootAdminSelects();
bootAdminDatePickers();
bootSearchableSelects();
bootColorInputs();
bootActionProgress();
bootBrandList();
bootAdminUserMenus();
bootCentralNavigation();
bootSiteAdminNavigation();
bootFilterDrawers();
bootFacetForms();
