<?php

return [
    'hero_search' => [
        'name' => 'Hero Search',
        'description' => 'Homepage hero with a catalog search entry point.',
        'category' => 'hero',
        'supported_page_types_json' => ['home'],
        'required_features_json' => [],
        'config_schema_json' => [
            'title' => 'string',
            'subtitle' => 'string',
            'search_placeholder' => 'string',
            'show_category_shortcuts' => 'boolean',
        ],
        'view_component' => 'blocks.hero-search',
    ],
    'popular_categories' => [
        'name' => 'Popular Categories',
        'description' => 'Shortcuts to categories enabled for the site.',
        'category' => 'navigation',
        'supported_page_types_json' => ['home'],
        'required_features_json' => [],
        'config_schema_json' => [
            'title' => 'string',
            'limit' => 'integer',
            'layout' => 'grid|list|chips',
        ],
        'view_component' => 'blocks.popular-categories',
    ],
    'top_products' => [
        'name' => 'Top Products',
        'description' => 'Placeholder for a future projected product selection.',
        'category' => 'products',
        'supported_page_types_json' => ['home'],
        'required_features_json' => [],
        'config_schema_json' => [
            'title' => 'string',
            'limit' => 'integer',
            'source' => 'rating|popular|manual|latest',
            'category_id' => 'integer',
            'layout' => 'grid|carousel|list',
        ],
        'view_component' => 'blocks.top-products',
    ],
    'latest_reviews' => [
        'name' => 'Latest Reviews',
        'description' => 'Placeholder for recent reviews supplied by the reviews module.',
        'category' => 'social_proof',
        'supported_page_types_json' => ['home'],
        'required_features_json' => ['reviews'],
        'config_schema_json' => [
            'title' => 'string',
            'limit' => 'integer',
            'min_rating' => 'integer',
            'layout' => 'cards|compact',
        ],
        'view_component' => 'blocks.latest-reviews',
    ],
    'lead_form' => [
        'name' => 'Lead Form',
        'description' => 'Placeholder for lead collection on home and product pages.',
        'category' => 'conversion',
        'supported_page_types_json' => ['home', 'product'],
        'required_features_json' => ['leads'],
        'config_schema_json' => [
            'title' => 'string',
            'lead_type' => 'repair|buying_advice|accessory_request|business_inquiry',
            'button_label' => 'string',
            'layout' => 'inline|card|sidebar',
        ],
        'view_component' => 'blocks.lead-form',
    ],
    'poll_block' => [
        'name' => 'Poll Block',
        'description' => 'Placeholder for polls on home, category, and product pages.',
        'category' => 'engagement',
        'supported_page_types_json' => ['home', 'category', 'product'],
        'required_features_json' => ['polls'],
        'config_schema_json' => [
            'title' => 'string',
            'poll_id' => 'integer',
            'placement' => 'inline|sidebar|card',
        ],
        'view_component' => 'blocks.poll-block',
    ],
    'buying_guides' => [
        'name' => 'Buying Guides',
        'description' => 'Placeholder for projected guides and editorial content.',
        'category' => 'content',
        'supported_page_types_json' => ['home', 'category'],
        'required_features_json' => ['guides'],
        'config_schema_json' => [
            'title' => 'string',
            'limit' => 'integer',
            'category_id' => 'integer',
            'content_type' => 'buying_guide|how_to_guide|article',
            'layout' => 'cards|list',
        ],
        'view_component' => 'blocks.buying-guides',
    ],
];
